kind = "mobile"
previewPath = "/mobile/"
title = "Magic Shop Mobile"
version = "1.0.0"
id = "artifacts/magic-shop-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 22791

[services.development]
run = "pnpm --filter @workspace/magic-shop-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/magic-shop-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/magic-shop-mobile", "run", "serve" ]

[services.env]
PORT = "22791"
BASE_PATH = "/mobile/"
